### PR TITLE
v1.2.1 electron 19

### PR DESCRIPTION
**Pull request by abebeos**
* This contains some non-relevant (to electron 19 update) changes.
* Removal of `electron-settings` may be reverted (new code is quasi-untested, was created on-the-fly)

### CODE REVIEW

**Comment by abebeos** [comment]
@Dexus, I remember that you had some kind of patch for `electron-settings`? Maybe you can 'revive' electron-settings at some point?

**Comment by Dexus** [comment]
Hi, I‘m not sure if I want to help right now, even xmas is at the door.

**Comment by abebeos** [comment]
> Hi, I‘m not sure if I want to help right now, even xmas is at the door.

Nothing urgent, just keep it in mind that the new settings-code is on-the-fly created.

**Comment by Dexus** [comment]
Maybe a quick fix:

```

...
... = new BrowserWindow({
  ...
  webPreferences: {
    enableRemoteModule: true
  },
  ...
})

```

**Comment by Dexus** [comment]
@abebeos do you need the sha to restore the changes to v1.2.2?

**Comment by abebeos** [comment]
@Dexus , all good, already done, see https://github.com/deepnest-io/Deepnest/releases/tag/v1.2.2

**Comment by abebeos** [comment]
The procedure was/is:

* add the remote
* fetch from remote
* `git cherry-pick <commit>` (adds the commit to the current branch)

me now fried brain, was not in a condition to plub in code, but wanted it done. 

If something comes up, just file issue, I'm possibly another 30 min. on the machine (and will maybe take a quick look tomorrow)

**Pull request merged**
