### PR TITLE
C++ better readable

### PR DESCRIPTION
**Pull request by Dexus**
based on #166 

it makes the c++ more readable for me

### CODE REVIEW

**Comment by Dexus** [comment]
Hmm I'm just a bit confused the c++ was building before now its build only on the nom install but not more on the `npm run build` I must have changed something in my environment on windows...

**Comment by abebeos** [comment]
> it makes the c++ more readable for me

better wait with this one.

General rule:

- agree on code-style
- one commit for general whitespace correction
- one commit for each style change (e.g. the "{}" indentation)

**Comment by abebeos** [comment]
@Dexus, the minkowski code is taken from the boost-library. Code should stay as identical as possible to the original one.

**Comment by Dexus** [comment]
> @Dexus, the minkowski code is taken from the boost-library. Code should stay as identical as possible to the original one.

Sure, I had already the idea to move this also to rust, when i find a way to get this robust enough with the same output as this c++ will produce. But had not yet the time to get deeper into c++ to analyze the complete workflow. 

Thats why its now a draft. Here and also because of the issues with electron >=32 if we not want to build our own version of electron ;)

We can also close it for now. 

I think there would be some faster options than this implementation. Had a test implementation in rust that was not full identical but 10-5 times faster. Even if it was only a test and did not produce the same result - i think there will be potential for improvements.

**Comment by abebeos** [comment]
closing, need to stabilize electron > 30 first.

**Pull request closed without merging**
