### PR TITLE
Add renovate Dashboard

### PR DESCRIPTION
**Pull request by bosd**

### CODE REVIEW

**Comment by abebeos** [comment]
can you please elaborate a little bit?

**Comment by bosd** [comment]
> can you please elaborate a little bit?

Renovate can provide a dashboard overview of which modules are used, and if there are updates available.
As you mentioned somewhere else, Automatic merging / bumping can lead to problems.
But maybe it is usefull to use it as an automated overview as an todo for lib updating.

**Comment by abebeos** [comment]
> But maybe it is usefull to use it as an automated overview as an todo for lib updating.

Sounds ok, we can try it!

**Comment by bosd** [comment]
@abebeos 
As to your ealier remark. (disabling automatic lib update by dependabot/ mend renovate)
Propably we want to look into the [approval section](https://docs.renovatebot.com/key-concepts/dashboard/#dependency-dashboard-approval-workflow) of the documentation.
Hmm, maybe not.. just let the bot make an PR, as a manual approval would be required to do the merge.

What are your thoughts?

**Comment by abebeos** [comment]
> What are your thoughts?

A dashboard is passive (I visit it whenever I want).

PRs are active, they appear and distract.

Personally, I do not like those bots, many times their PRs a re just ignored.

Another thing are security related update notices (like e.g. here: https://github.com/deepnest-io/Deepnest/security/dependabot).

So, for now, if the Dashboard can be activated, without activating the PRs, then it should/can be done.

Otherwise just await until the manual updates are done.

**Comment by abebeos** [comment]
merging, so the dashboard is tried when renovate is enabled in future.

**Pull request merged**
